---
title: "Results - Overall"
---
```{r, echo=FALSE, message=FALSE, warning=FALSE}
htmltools::img(src = knitr::image_uri("code/ssari_logo.jpeg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; width:20%; height:auto;')
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)

data_ssari <- readRDS("cleaned_data/sprit_sari_annual_report_2023_dataset.rds")

data_ssari <- data_ssari %>% 
  group_by(subjid) %>%
  fill(hostdat_icu, .direction = 'updown') %>%
  filter(hostdat_icu <= "2023-12-31")

data_baseline <- data_ssari %>% 
  group_by(subjid) %>%
  fill(apache_score, .direction = 'updown') %>%
  slice(1) %>%
  ungroup()
```

## Annual incidence and pathogen proportion

### Figure 1. Annual number of SARI cases
```{r echo=FALSE, fig.height=8, fig.width=10, message=FALSE, warning=FALSE}
library(ggpubr)
data_baseline %>%
  mutate(icu_admission_month = paste0(format(hostdat_icu, "%Y"),"-"  , format(hostdat_icu, "%m"))) %>% 
  group_by(icu_admission_month) %>%
  summarise(n = n(), 
            year = format(hostdat_icu, "%Y")) %>%
  distinct() %>%
  group_by(year) %>%
  mutate(n_yearly = sum(n)) %>%
  arrange(icu_admission_month) %>%
  ggplot(aes(x = icu_admission_month, y = n, fill = year)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_d(option = "viridis", direction = 1) +
  annotate("rect", xmin = 0, xmax = 9.5, ymin = 0, ymax = 700, fill = "#AF7AC5", alpha = 0.2) +
  annotate("rect", xmin = 9.5, xmax = 21.5, ymin = 0, ymax = 3100, fill = "#7FB3D5", alpha = 0.2) +
  annotate("rect", xmin = 21.5, xmax = 33.5, ymin = 0, ymax = 5300, fill = "#A9DFBF", alpha = 0.2) +
  annotate("rect", xmin = 33.5, xmax = 46, ymin = 0, ymax = 3300, fill = "#F9E79F", alpha = 0.2) +
  annotate("text", x = 5, y = 700, label = "n = 628", color = "#76448A", vjust = -.5) +
  annotate("text", x = 16, y = 3100, label = "n = 3,026", color = "#2471A3", vjust = -.5) +
  annotate("text", x = 28, y = 5300, label = "n = 5,218", color = "#1E8449", vjust = -.5) +
  annotate("text", x = 40, y = 3300, label = "n = 3,309", color = "#D4AC0D", vjust = -.5) +
  theme_pubclean() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Number of SARI cases") +
  xlab("Month of ICU admission") +
  theme(legend.title = element_blank())
```

### Figure 2. Pathogen proportion
```{r echo=FALSE, fig.width=10, message=FALSE, warning=FALSE}
library(forcats)

pathogen_data <- data_baseline %>%
  mutate(if_other_please_specify = tolower(if_other_please_specify)) %>%
  mutate(corona_ieorres = ifelse(grepl("covid", if_other_please_specify) | grepl("coronavirus", if_other_please_specify), 1, corona_ieorres),
         haemophilus = ifelse(grepl("haemophilus", if_other_please_specify), 1, 0),
         noncovid___1 = ifelse(grepl("influenza", if_other_please_specify), 1, noncovid___1),
         noncovid___2 = ifelse(grepl("flu", if_other_please_specify), 1, noncovid___2),
         noncovid___3 = ifelse(grepl("rsv", if_other_please_specify), 1, noncovid___3),
         noncovid___4 = ifelse(grepl("parainfluenza", if_other_please_specify), 1, noncovid___4),
         adenovirus = ifelse(grepl("adeno", if_other_please_specify), 1, 0),
         metapneumovirus = ifelse(grepl("metapneumovirus", if_other_please_specify) | 
                                    grepl("hmpv", if_other_please_specify)
                                  , 1, 0),
         entero_rhinovirus = ifelse(grepl("rhino", if_other_please_specify) | grepl("entero", if_other_please_specify), 1, 0),
         mycoplasma = ifelse(grepl("mycoplasma", if_other_please_specify), 1, 0),
  ) %>%
  mutate(pathogen = case_when(haemophilus == 1 ~ "Other",
                              corona_ieorres == 1 ~ "COVID-19",
                              noncovid___1 == 1 ~ "Influenza", 
                              noncovid___2 == 1 ~ "Influenza",
                              noncovid___3 == 1 ~ "Respiratory syncytial virus",
                              noncovid___4 == 1 ~ "Parainfluenza",
                              adenovirus == 1 ~ "Adenovirus",
                              metapneumovirus == 1 ~ "Metapneumovirus",
                              entero_rhinovirus == 1 ~ "Entero/Rhinovirus",
                              mycoplasma == 1 ~ "Other",
                              .default = "Other")) 

pathogen_data %>%
  select(pathogen) %>%
  group_by(pathogen) %>%
  summarise(prop = n()/nrow(data_baseline) * 100, 
            n = n()) %>%
  mutate(pathogen = fct_reorder(pathogen, prop)) %>%
  ggplot(aes(x = reorder(pathogen, prop), y = prop, fill = reorder(pathogen, prop))) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  scale_fill_viridis_d(option = "rocket", direction = 1) + 
  theme_pubclean() + 
  theme(legend.position = "none") + 
  ylab("Proportion (%)") + 
  xlab("") + 
  geom_text(aes(label = paste0(round(prop, 1), "%, n = ", n)), hjust = -0.1) +
  ylim(0, 100) 
```

### Figure 3. Pathogen proportion by year
```{r echo=FALSE, fig.height=8, fig.width=10, message=FALSE, warning=FALSE}

pathogen_data %>%
  mutate(icu_admission_month = paste0(format(hostdat_icu, "%Y"),"-"  , format(hostdat_icu, "%m")),
         year = format(hostdat_icu, "%Y")) %>% 
  group_by(year) %>%
  mutate(n_pop = n()) %>%
  group_by(pathogen, year) %>%
  summarise(n = n(), 
            prop = (n() / n_pop) * 100) %>%
  distinct() %>%
  ggplot(aes(x = year, y = prop)) +
  geom_bar(stat = "identity", aes(fill = reorder(pathogen, prop))) +
  scale_fill_viridis_d(option = "rocket", direction = 1) +
  theme_pubclean() +
  ylab("Proportion (%)") +
  xlab("Year of ICU admission") +
  theme(legend.title = element_blank())
```


### Table 1. Pathogen proportion by year
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(gtsummary)
library(gt)

pathogen_data %>% 
  mutate(year = format(hostdat_icu, "%Y")) %>%
  select(pathogen, year) %>%
  tbl_summary(by = year, 
              label = list(pathogen ~ "Pathogen, n (%)"), 
              statistic = list(all_categorical() ~ "{n} ({p})"), 
              sort = list(everything() ~ 'frequency')) %>% 
  add_overall() %>%
  modify_header(all_stat_cols() ~ md("**{level}**
  
                                     (N = {n})"),
                label = "**Variables**") %>% 
  modify_footnote(everything() ~ NA) %>% 
  as_gt() %>% 
  tab_style(style = list(cell_text(weight = "bold")),
            locations = cells_group()) %>%
  opt_stylize(style = 6, color = "blue", add_row_striping = TRUE)
```
\

## Demographics

### Table 2. Baseline characteristics
```{r echo=FALSE, message=FALSE, warning=FALSE}
data_baseline %>%
  mutate(corona_ieorres = ifelse(is.na(corona_ieorres), 0, corona_ieorres)) %>% 
  mutate(corona_ieorres = ifelse(corona_ieorres == 1, "COVID-19", "Non-COVID-19")) %>%
  mutate(period = ifelse(hostdat_icu <= "2022-12-31", "2020-2022", "2023")) %>%
  select(age_estimateyears, 
         sex, 
         bmi_calc, 
         obesity_mhyn,
         pregyn_rptestcd,
         apache_score,
         chroniccard_mhyn,
         aceinhibitor_myhn,
         obesity_mhyn,
         chronicpul_mhyn,
         diabetiscomp_mhyn,
         diabetes_mhyn,
         asthma_mhyn,
         renal_mhyn,
         rheumatology_mhyr,
         mildliv_mhyn,
         modliver_mhyn,
         dementia_mhyn,
         malnutrition_mhyn,
         chronicneu_mhyn,
         malignantneo_mhyn,
         other_mhyn,
         chronhaemo_mhyn,
         aidshiv_mhyn,
         chrimm_mhyn,
         daily_fio2_lborres,
         daily_pao2_lborres,
         daily_pco2_lborres,
         daily_ph_lborres,
         daily_hco3_lborres,
         daily_gcs_vsorres,
         daily_lactate_lborres,
         corona_ieorres,
         period
         ) %>% 
  tbl_summary(by = period, 
              missing = "no",
              label = list(age_estimateyears ~ "Age (years)")
              
              ) %>% 
   add_overall() %>%
   add_n()
  

```