# Library import

```{r}
library(dplyr)
library(tidyverse)
library(Hmisc) # for the label function
```

# Data Import

```{r}
data_ssari <- read_csv("raw_data/NovelCoronavirusCOVI_DATA_2024-07-01_1058.csv")
data_duplicate <- readxl::read_excel("raw_data/log_duplicate_19DEC22.xlsx")
date_report <- Sys.Date()
```

# Data Cleaning from Ary

```{r}
data_ssari %>% group_by(subjid) 
```


```{r}
#Custom Function#
source("code/Ary_functions.R")
carry_worst <- function(x) {
  x <- ifelse(x-lag(x)==1, 1, x)
}


#Change enviroment to English#
Sys.setlocale("LC_TIME", "C")


#Get only IDs Duplicated#
data_id <- data_duplicate %>%
  na.omit() %>%
  filter(transfer_readmission!="readmission" & first_id!="108-0011") %>% #CHECK
  mutate(same_id = seq(1, nrow(.), 1)) %>% #grouping the ID from a same patients by the same indicator
  select(first_id, second_id, same_id) %>%
  gather(key, subjid, -same_id) %>%
  arrange(same_id) %>%
  mutate(same_id_seq = ifelse(key=="first_id", paste(same_id, 1, sep = "_"), paste(same_id, 2, sep = "_"))) %>% #classifying the first admission as "_1" and the second as "_2"
  select(same_id, same_id_seq, subjid) %>%
  arrange(same_id, same_id_seq, subjid)


#Keep re-admissions as two different IDs (exclude from the Log)#
#Extract the duplicated records from the overall dataset and treat them#
data_dup_raw <- data_ssari %>%
  mutate_if(is.character, empty_to_NA) %>%
  filter(subjid %in% data_id$subjid) %>% #extracting from the overal dataset all patients indicated as duplicated
  left_join(data_id, by = "subjid") %>% #joining the unique IDs from the other dataset
  #select(359:360,223,1:357) %>%
  mutate(daily_dsstdat = as.Date(daily_dsstdat), hostdat = as.POSIXct(hostdat, format = "%Y-%m-%d %H:%M"), hostdat_icu = as.POSIXct(hostdat_icu, format = "%Y-%m-%d %H:%M"), 
         dsstdtc_icudate = as.POSIXct(dsstdtc_icudate, format = "%Y-%m-%d %H:%M"), dsstdtc = as.POSIXct(dsstdtc, format = "%Y-%m-%d %H:%M"), cestdat = as.Date(cestdat)) %>% 
  arrange(same_id, same_id_seq) %>%
  group_by(same_id, redcap_event_name) %>%
  fill(daily_dsstdat, .direction = "downup") %>%
  ungroup() %>%
  arrange(daily_dsstdat, same_id_seq) %>%
  group_by(same_id, redcap_event_name) %>%
  fill(apache_score, .direction = "up") %>%
  mutate(hostdat = if_else(grepl("_2", same_id_seq), as.character(NA), as.character(hostdat)), hostdat_icu = if_else(grepl("_2", same_id_seq), as.character(NA), as.character(hostdat_icu)),
         cestdat = if_else(grepl("_2", same_id_seq), as.character(NA), as.character(cestdat)), apache_score = ifelse(grepl("_2", same_id_seq), NA, apache_score),
         hostdat = as.POSIXct(hostdat, format = "%Y-%m-%d %H:%M"), hostdat_icu = as.POSIXct(hostdat_icu, format = "%Y-%m-%d %H:%M"), cestdat = as.Date(cestdat),
         dsstdtc = if_else(grepl("_1", same_id_seq), as.character(NA), as.character(dsstdtc)), dsstdtc_icudate = if_else(grepl("_1", same_id_seq), as.character(NA), as.character(dsstdtc_icudate)),
         dsstdtc_icudate = as.POSIXct(dsstdtc_icudate, format = "%Y-%m-%d %H:%M"), dsstdtc = as.POSIXct(dsstdtc, format = "%Y-%m-%d %H:%M")) %>% #getting the symptoms. ICU and Hospital admission date of the first admission
  group_by(same_id) %>%
  fill(c(hostdat, hostdat_icu, cestdat, dsstdtc_icudate, dsstdtc), .direction = "downup") %>%
  group_by(same_id, redcap_event_name) %>%
  fill(apache_score, .direction = "down") %>%
  group_by(same_id) %>%
  mutate(test = if_else(daily_dsstdat==lead(daily_dsstdat), 1, 0, missing=0)) %>% #temporary variable to exclude the last daily entry for admission #1 as it overlaps with the first daily entry from the second admission. 
  filter(test!=1) %>% #filtering
  ungroup() %>%
  mutate_at(vars(viralpneu_ceterm:myocarditis_ceterm), ~na_if(., 3)) %>% #replacing 3 by NA in this variables#
  group_by(same_id, redcap_event_name) %>%
  fill(c(viralpneu_ceterm:myocarditis_ceterm,antiviral_cmyn:hydroxy_therapy,antiviral_cmtrt_2,antiviral_cmtrt_3), .direction = "downup") %>%
  mutate_at(vars(viralpneu_ceterm:myocarditis_ceterm,antiviral_cmyn:antiviral_cmtrt,corticost_cmroute___1:monoclonals_type,dsstdtc_icudate:outcm_chest,dsterm_2:otherhosplocation,hydroxy_therapy,antiviral_cmtrt_2,antiviral_cmtrt_3), carry_worst) %>% #keep YES when YES at any moment
  mutate(test = if_else(redcap_event_name=="dischargeoutcome_arm_1" & grepl("_1", same_id_seq), 1, 0)) %>% #temporary variable to exclude the 'dischargeoutcome_arm_1' from the first admission
  filter(test!=1) %>% #filtering
  select(-test) %>%
  ungroup() %>%
  arrange(same_id, daily_dsstdat) %>%
  group_by(same_id) %>%
  mutate(day = row_number(), day = ifelse(redcap_event_name=="dischargeoutcome_arm_1", NA, ifelse(day>14, 14, day)), 
         redcap_event_name = ifelse(redcap_event_name=="dischargeoutcome_arm_1", "dischargeoutcome_arm_1", paste("day_", day, "_arm_1", sep = "")),
         test = ifelse(day<14, 0, 1), redcap_repeat_instance = ifelse(day==14, cumsum(test), NA)) %>%
  mutate(subjid = ifelse(grepl("_1", same_id_seq), NA, subjid)) %>%
  group_by(same_id) %>%
  fill(subjid, .direction = "downup") %>%
  ungroup() %>%
  mutate(transferred = 1, 
         dsstdtc_icudate = as.POSIXct(dsstdtc_icudate, format = "%Y-%m-%d %H:%M"), dsstdtc = as.POSIXct(dsstdtc, format = "%Y-%m-%d %H:%M")) %>%
  select(-c(day, test, same_id, same_id_seq))


#Exclude the duplicates from the overall dataset#
data_ssari <- data_ssari %>%
  filter(!subjid %in% data_id$subjid) %>% #Excluding the duplicates from the overall dataset
  arrange(subjid, daily_dsstdat) %>%
  mutate(transferred = 0,
         day = row_number(), day = ifelse(redcap_event_name=="dischargeoutcome_arm_1", NA, ifelse(day>14, 14, day)), 
         test = ifelse(day<14, 0, 1), redcap_repeat_instance = ifelse(day==14, cumsum(test), NA)) %>%
  select(-c(day, test)) %>%
  bind_rows(data_dup_raw) %>% #Binding the consolidated duplicates in the new dataset
  mutate(dsterm_2 = ifelse(subjid=="012-0001" | subjid=="012-0002" | subjid=="012-0003" | subjid=="012-0004" | subjid=="012-0006" | subjid=="012-0007" | subjid=="012-0037" | subjid=="133-0005", 2, dsterm_2),
         dsterm_2 = ifelse(subjid=="060-0001", 3, dsterm_2)) %>%
  mutate_if(is.character, empty_to_NA)

data_ssari <- data_ssari %>%
	mutate_if(is.character, empty_to_NA) %>%
	mutate(state = ifelse(grepl("001|003", redcap_data_access_group), "NT", 
				   ifelse(grepl("011|057|128|136|169|235|249|279|345", redcap_data_access_group), "WA", 
				   ifelse(grepl("006|007|034|045|101|116|216|284", redcap_data_access_group), "SA", 
				   ifelse(grepl("004", redcap_data_access_group), "ACT",
				   ifelse(grepl("113|138", redcap_data_access_group), "TAS",
				   ifelse(grepl("019|020|026|040|042|051|117|123|149|168|186|205|223|224|286", redcap_data_access_group), "QLD",
				   ifelse(grepl("008|012|014|033|046|079|080|111|115|127|131|142|163|210|277|283", redcap_data_access_group), "NSW", "VIC"))))))),
			hostdat = as.POSIXct(hostdat, format = "%Y-%m-%d %H:%M"),
			phase = if_else(as.Date(as.POSIXct(hostdat_icu, format = "%Y-%m-%d %H:%M"), tz = "")<"2020-07-01", 1, 
				   if_else(as.Date(as.POSIXct(hostdat_icu, format = "%Y-%m-%d %H:%M"), tz = "")>"2021-06-25", 3, 2)), 
		    phase = if_else(is.na(phase), 3, phase), 
		    phase = ifelse(redcap_event_name=="day_1_arm_1", phase, NA)) %>%
	group_by(subjid) %>%
	fill(phase, corona_ieorres_2, age_estimateyears, hostdat, .direction = "downup") %>%
	ungroup() %>%
	mutate(variant = ifelse(as.Date(hostdat)<="2020-12-20", 0, variant),
		   corona_ieorres_2 = ifelse(phase==3 & is.na(corona_ieorres_2), 3, corona_ieorres_2)) %>%
	mutate_at(vars(covid_vac), make_binary)

#Correct daily data#
custom <- function(x){
  x = as.Date(as.POSIXct(x, format = "%Y-%m-%d %H:%M"), tz = "")
}
test <- data_ssari %>%
  mutate_if(is.character, empty_to_NA) %>%
  filter(redcap_event_name=="dischargeoutcome_arm_1") %>%
  select(subjid, imv1_start, imv1_stop, ecmo1_start, ecmo1_stop, trache_start, trache_stop, hfnc_start, hfnc_stop, bipap_start, bipap_stop, cpap_start, cpap_stop, vasop_inot_start, vasop_inot_stop, dialysis_start,
         dialysis_stop, prone_pos_start, prone_pos_stop) %>%
  mutate_at(vars(imv1_start:prone_pos_stop), custom) %>%
  gather(key, daily_dsstdat, imv1_start:prone_pos_stop) %>%
  arrange(subjid, key, daily_dsstdat) %>%
  mutate(variable = gsub("_start", "", key), variable = gsub("_stop", "", variable)) %>%
  select(-key) %>%
  group_by(subjid, variable) %>%
  mutate(daily_dsstdat = if_else(!is.na(lag(daily_dsstdat)) & (is.na(daily_dsstdat) | daily_dsstdat>date_report), date_report, daily_dsstdat)) %>%
  ungroup() %>%
  na.omit() %>%
  group_by(subjid, variable) %>%
  complete(daily_dsstdat = full_seq(daily_dsstdat, 1)) %>%
  ungroup() %>%
  arrange(subjid, variable, daily_dsstdat) %>%
  mutate(value = 1,
         variable = case_when(variable=="imv1" ~ "daily_invasive_prtrt1",
                              variable=="ecmo1" ~ "daily_ecmo_prtrt1",
                              variable=="dialysis" ~ "daily_rrt_cmtrt1",
                              variable=="hfnc" ~ "daily_nasaloxy_cmtrt1",
                              variable=="prone_pos" ~ "daily_prone_cmtrt1",
                              variable=="trache" ~ "daily_trach_prperf1",
                              variable=="vasop_inot" ~ "daily_inotrope_cmyn1", TRUE ~ NA_character_)) %>%
  group_by(subjid, variable) %>%
  filter(!duplicated(daily_dsstdat)) %>%
  ungroup() %>%
  spread(variable, value) 

final <- data_ssari %>%
  left_join(test, by = c("subjid","daily_dsstdat")) 
```

```{r}
data_ssari <- data_ssari %>% 
  mutate_at(c(grep("_mhyn", colnames(data_ssari), value = TRUE), 
              "sex", 
              "rheumatology_mhyr"), 
            function(x) { ifelse(x == 3, NA, x)
            }) %>% 
  mutate_at(c(grep("_mhyn", colnames(data_ssari), value = TRUE), 
              "imv_1",
              "ecmo1",
              "trache",
              "rheumatology_mhyr"), 
            function(x) {ifelse(x == 2, 0, x)
              }) %>%
  mutate(pregyn_rptestcd = ifelse(!pregyn_rptestcd %in% c(0,1), NA, pregyn_rptestcd)) %>%
  mutate(outcm_cod = case_when(outcm_cod == 1 ~ "Treatment withdrawn, prognosis poor",
                               outcm_cod == 2 ~ "Brain injury",
                               outcm_cod == 3 ~ "Brain death",
                               outcm_cod == 4 ~ "Arrhythmia",
                               outcm_cod == 5 ~ "Cardiogenic shock",
                               outcm_cod == 6 ~ "Distributive (Septic) shock",
                               outcm_cod == 7 ~ "Hypovolaemic shock",
                               outcm_cod == 8 ~ "Hypoxic respiratory failure",
                               outcm_cod == 9 ~ "Metabolic",
                               outcm_cod == 10 ~ "Other"), 
         dsterm = case_when(dsterm == 1 ~ "Discharged home",
                            dsterm == 2 ~ "Transfer to other facility (acute hospital)",
                            dsterm == 3 ~ "Transfer to another facility (rehab)",
                            dsterm == 4 ~ "Palliative discharge",
                            dsterm == 5 ~ "Unknown",
                            dsterm == 6 ~ "Death"),
         dsterm_2 = case_when(dsterm_2 == 1 ~ "Death",
                              dsterm_2 == 2 ~ "Wards",
                              dsterm_2 == 3 ~ "Other hospital",
                              dsterm_2 == 4 ~ "Other rehab",
                              dsterm_2 == 5 ~ "Home")
         ) %>%
  group_by(subjid) %>%
  mutate(vasop_inot_sup = ifelse(any(daily_inotrope_cmyn == 1, na.rm = TRUE), 1, 0)) %>%
  mutate(vasop_inot_sup = ifelse(any(vasop_inot_sup == 1, na.rm = TRUE), 1, vasop_inot_sup)) %>%
  ungroup() 
```

```{r}
data_ssari <- data_ssari %>% 
  select(subjid, 
         hostdat_icu,
         noncovid___1,
         noncovid___2,
         noncovid___3,
         noncovid___4,
         age_estimateyears, 
         sex, 
         bmi_calc, 
         obesity_mhyn,
         pregyn_rptestcd,
         apache_score,
         corona_ieorres,
         chroniccard_mhyn,
         obesity_mhyn,
         chronicpul_mhyn,
         diabetes_mhyn,
         diabetiscomp_mhyn,
         asthma_mhyn,
         renal_mhyn,
         rheumatology_mhyr,
         mildliv_mhyn,
         modliver_mhyn,
         dementia_mhyn,
         malnutrition_mhyn,
         chronicneu_mhyn,
         malignantneo_mhyn,
         chronhaemo_mhyn,
         aidshiv_mhyn,
         chrimm_mhyn,
         imv_1,
         if_other_please_specify,
         dura_vm1_reportonly,
         ecmo1,
         prone_pos,
         vasop_inot_sup,
         dialysis, 
         icu_los_reportonly,
         hosp_los_reportonly,
         hostdat,
         dsstdtc,
         dsstdtc_icudate,
         dsterm_2,
         dsterm,
         outcm_cod) %>%
  group_by(subjid) %>%
  fill(everything(), .direction = "updown")
```

```{r}
saveRDS(data_ssari, paste0("cleaned_data/", Sys.Date(), "_sprit_sari_annual_report_dataset.rds"))
```
